Repository bong-dari/BongdariFrontend, pull requests merged in 2021-05, with the labels that each got.

#1 config: 프로젝트 초기 셋팅
  .buckconfig
  .editorconfig
  .eslintrc.js
  .flowconfig
  .gitattributes
  .gitignore
  .nvmrc
  .prettierrc.js
  .watchmanconfig
  App.js
  __tests__/App-test.js
  android/app/_BUCK
  android/app/build.gradle
  android/app/build_defs.bzl
  android/app/debug.keystore
  android/app/proguard-rules.pro
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/com/bongdarifrontend/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/bongdarifrontend/MainActivity.java
  android/app/src/main/java/com/bongdarifrontend/MainApplication.java
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  app.json
  babel.config.js
  index.js
  ios/BongdariFrontend.xcodeproj/project.pbxproj
  ios/BongdariFrontend.xcodeproj/xcshareddata/xcschemes/BongdariFrontend.xcscheme
  ios/BongdariFrontend.xcworkspace/contents.xcworkspacedata
  ios/BongdariFrontend/AppDelegate.h
  ios/BongdariFrontend/AppDelegate.m
  ios/BongdariFrontend/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/BongdariFrontend/Images.xcassets/Contents.json
  ios/BongdariFrontend/Info.plist
  ios/BongdariFrontend/LaunchScreen.storyboard
  ios/BongdariFrontend/main.m
  ios/BongdariFrontendTests/BongdariFrontendTests.m
  ios/BongdariFrontendTests/Info.plist
  ios/Podfile
  ios/Podfile.lock
  metro.config.js
  package.json
Labels: config

#3 멤버 회원가입 뷰 구현
  App.js
  index.js
  package.json
  src/assets/images/kakaoIcon.png
  src/assets/images/naverIcon.png
  src/components/member/Login.js
Labels: feature

#5 멤버 추가정보 뷰 구현
  App.js
  package.json
  src/assets/global.js
  src/components/member/AddInfo.js
  src/components/member/Login.js
Labels: feature

#7 멤버 약관 뷰 구현
  App.js
  package.json
  src/screens/member/AddInfo.js
  src/screens/member/Login.js
  src/screens/member/Terms.js
Labels: feature

#11 공통 버튼 컴포넌트 구현
  src/assets/global.js
  src/assets/globalStyles.js
  src/screens/member/AddInfo.js
  src/screens/member/Terms.js
Labels: feature

#13 기관 로그인 뷰 구현
  App.js
  src/screens/institution/InstitutionAddressForm.js
  src/screens/institution/InstitutionContactForm.js
  src/screens/institution/InstitutionIdForm.js
  src/screens/institution/InstitutionLogin.js
  src/screens/institution/InstitutionNameForm.js
  src/screens/institution/InstitutionPwForm.js
  src/screens/institution/InstitutionSNForm.js
  src/screens/member/MemberAddInfo.js
  src/screens/member/MemberLogin.js
  src/screens/member/MemberTerms.js
Labels: feature

#22 추가정보 입력 뷰 수정
  src/screens/institution/InstitutionAddressForm.js
  src/screens/institution/InstitutionContactForm.js
  src/screens/institution/InstitutionIdForm.js
  src/screens/institution/InstitutionNameForm.js
  src/screens/institution/InstitutionPwForm.js
  src/screens/institution/InstitutionSNForm.js
  src/screens/member/MemberAddInfo.js
  src/screens/member/MemberAddName.js
  src/screens/member/MemberTerms.js
Labels: fix

#25 유저 게시판 Tab Navigation 스크린 이동 구현
  package.json
  src/screens/board/Board1.js
  src/screens/board/Board2.js
  src/screens/board/Board3.js
  src/screens/board/BoardTabScreen.js
  src/screens/member/MemberTerms.js
Labels: feature

#26 옆동네 봉사 게시판 리스트 레이아웃 구현
  App.js
  src/components/board/BoardSearchBar.js
  src/components/board/BoardTabBar.js
  src/screens/board/Board1.js
  src/screens/board/Board2.js
  src/screens/board/Board3.js
  src/screens/board/BoardTabScreen.js
  src/screens/institution/InstitutionPwForm.js
Labels: feature

#27 유저 게시판 구현 마무리
  src/components/board/BoardSearchBar.js
  src/components/board/BoardTabBar.js
  src/screens/board/Board1.js
  src/screens/board/Board2.js
  src/screens/board/Board3.js
  src/screens/board/BoardTabScreen.js
Labels: feature

#31 페이지 뒤로가기 기능 구현
  App.js
  package.json
  src/screens/common/GobackButton.js
Labels: feature

#35 공통 지역 검색 컴포넌트 레이아웃 구현
  src/screens/board/Board1.js
  src/screens/board/Board2.js
  src/screens/board/Board3.js
  src/screens/bottom/AreaScreen.js
  src/screens/bottom/MainTabStackScreen.js
Labels: feature
